### ISSUE TITLE
Unable to rebuild the solution

### ISSUE THREAD

**Issue by yobeidat** [Esri/route-planner-csharp#27]
Dear Rodney Conger,

When I try to rebuild the solution I get the error below. Could you please give me any useful information in order to fix it.
![error](https://cloud.githubusercontent.com/assets/17982604/13918201/514225ac-ef6e-11e5-85bb-f83e297b9253.PNG)

Regards,

**Comment by neran27** [comment]
Me too getting the same.

**Comment by neran27** [comment]
ON deleting the license key file from arclogistics.app the soln is getting build.

**Comment by yobeidat** [comment]
Thank you Narendra for your response But I could not find any license file in arclogistics.app but a shortcut for the license file in the main directory of the project.Could you please tell me the path of the file that you've deleted.
Many Thanks,

**Comment by neran27** [comment]
after extracting the zip, if you open the soln, in VS, you will be seeing the license file, in the following path:

route-planner-csharp-master\route-planner-csharp-master\RoutePlanner_DeveloperTools\Source\ArcLogisticsApp\Properties\licenses.licx

**Comment by jwickstrom** [comment]
The problem is likely with the ActiveReports licensing (or lack thereof).  Open up \ArcLogisticsApp\Properties\licenses.licx.  If you see in there “PublicKeyToken=abcdef… “ ActiveReports is not yet licensed.

You will need to obtain the "old" version of this component as specified in the readme and follow the steps.  You run a special app to get a key, etc. 

Deleting the file may work as well.  I think this will overlay "NOT LICENSED" or similar in the reports.
